### ISSUE TITLE
Export PDF file

### ISSUE THREAD

**Issue by codenuk** [InFacts/srt_cmms_frontend#54]
## เอกสารที่ต้อง Export to PDF
- [ ] ส.16/46

- [x] ส.1

- [ ] บ.22

- [ ] สส.101

- [ ] สรุปปฏิบัติการทำวาระบำรุงรักษาประจำเดือน

<img width="968" alt="Screen Shot 2563-06-11 at 13 12 03" src="https://user-images.githubusercontent.com/34050939/84351379-7959a500-abe5-11ea-820c-ad897d8fe461.png">

<img width="982" alt="Screen Shot 2563-06-11 at 13 12 08" src="https://user-images.githubusercontent.com/34050939/84351389-7c549580-abe5-11ea-9823-083bd8d923c9.png">

<img width="1049" alt="Screen Shot 2563-06-11 at 16 04 44" src="https://user-images.githubusercontent.com/34050939/84366676-5b983a00-abfd-11ea-818c-b079d17e7621.png">

**Comment by SorawitSiri** [comment]
### PATH: /src/js/helper.js
เขียน Function แต่ละ component ต้องการใช้บ่อยๆ
https://github.com/InFacts/srt_cmms_frontend/blob/1209122696034e6d300d6496c9c1ca421da44e4f/src/js/helper.js#L763-L809

**Comment by SorawitSiri** [comment]
### Action Step

1. Create function in path `/src/js/helper.js`
```
export const checkDocumentStatus = (valuesContext) => {
      // You can code for Get value from Context & Export to PDF File
}
```

**Comment by SorawitSiri** [comment]
**เต้ต้อง dispatch ไป function นี้**
https://github.com/InFacts/srt_cmms_frontend/blob/4145bf55a4ba2d973dfbf03a913b9db917500634/src/js/redux/modules/toolbar.js#L210

**ซึ่งฟังก์ด้านบนไปเปลี่ยนค่าเป็น false ให้**
https://github.com/InFacts/srt_cmms_frontend/blob/4145bf55a4ba2d973dfbf03a913b9db917500634/src/js/redux/modules/toolbar.js#L176-L181


**วิธี dispatch**
https://github.com/InFacts/srt_cmms_frontend/blob/4145bf55a4ba2d973dfbf03a913b9db917500634/src/js/hooks/footer-initializer.js#L446

แต่ต้องเปลี่ยน 
```
ACTION_TO_HANDLE_CLICK[FOOTER_ACTIONS.FAST_TRACK]()
```
เป็นด้านล่าง ซึ่งต้อง import function มาด้วยนะ
```
handleClickExportPDF()
```
