### ISSUE TITLE
Add footer in item master data and warehouse master data

### ISSUE THREAD

**Issue by codenuk** [InFacts/srt_cmms_frontend#56]
บันทึก กับ ย้อนกลับ ในโหมด Add
ย้อนกลับ ในโหมด search

**Comment by SorawitSiri** [comment]
I implemented. :D
https://github.com/InFacts/srt_cmms_frontend/blob/6575cc2f52093eb1f8b474dbaa46e52242402a2b/src/js/hooks/footer-initializer.js#L134-L143
