### ISSUE TITLE
SS101 Fact Querying

### ISSUE THREAD

**Issue by Knight-H** [InFacts/srt_cmms_frontend#61]
The new API has /fact/ss101/{FACTS} , query them and put them inside the SS101 Component Selects.

**Comment by codenuk** [comment]
Finish Querying But Not have data mockup

**Comment by codenuk** [comment]
`const factAccidentCause = useSelector((state) => ({ ...state.api.fact[FACTS.SS101_ACCIDENT_CAUSE] }), shallowEqual);`
`const factCaseType = useSelector((state) => ({ ...state.api.fact[FACTS.SS101_CASE_TYPE] }), shallowEqual);`
สองอันนี้ไม่ได้เอามาใส่ ใน Look Up
