### ISSUE TITLE
Bug Footer in Page Master Data Not Show ส่งเอกสาร

### ISSUE THREAD

**Issue by codenuk** [InFacts/srt_cmms_frontend#67]
![Screen Shot 2563-06-13 at 23 27 48](https://user-images.githubusercontent.com/29748024/84573916-93ee7280-adcd-11ea-8d06-63452e0abee7.png)
<img width="1294" alt="Screen Shot 2563-06-13 at 23 28 27" src="https://user-images.githubusercontent.com/29748024/84573921-9650cc80-adcd-11ea-914d-f6a300676e19.png">

**Comment by SorawitSiri** [comment]
4c3d49918049f7ef82f512103277845c53cf075c
wait Permission for admin

**Comment by SorawitSiri** [comment]
Closed by 461dbaa522e3d183e46cb62c954d4a6af2d72f20
