### ISSUE TITLE
ปุ่ม สำหรับ บันทึก ในหน้า Admin

### ISSUE THREAD

**Issue by codenuk** [InFacts/srt_cmms_frontend#73]
<img width="1552" alt="Screen Shot 2563-06-17 at 18 10 59" src="https://user-images.githubusercontent.com/29748024/84891369-f72a1e80-b0c5-11ea-81bc-cdb8244eaecb.png">

**Comment by SorawitSiri** [comment]
มีคนแก้ไปแล้ว
